In [1]:
import numpy as np

In [4]:
print('ONE DIMENTIONAL ARRAY')
l = [5,6,7,8]
y=np.array(l)
x= np.array([1,2,3,4])
x
print(y)

ONE DIMENTIONAL ARRAY
[5 6 7 8]


In [7]:
l = [5,6,7,8]
a = np.array(l)
print(a, 'array do not have comma')
print(l ,'lsit have comma')

[5 6 7 8]
[5, 6, 7, 8]


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
import numpy as np
l1=[5,6,7,8]
l2=[6,7,8,9]
a=np.array([l1,l2])
print(a)
print(type(a))

[[5 6 7 8]
 [6 7 8 9]]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
a=np.array([[5,6,7,8],[6,7,8,9],[11,7,8,9]])
print(a)
print(type(a))

[[ 5  6  7  8]
 [ 6  7  8  9]
 [11  7  8  9]]
<class 'numpy.ndarray'>


## How array are stored?
##  1.  Axes:An array can be 1d,2d or Multi Dimensional
##    Numpy refer to dimension of arrays as axis
##    Axis0=1d,axis1=2d,axis2=3d ...... so on
###     2. Rank:Number of axes
###     3. Shape:Number of elements along each axis of it.
###            shape is in the form of tuple.


In [13]:
a=np.array([[5,6,7,8],[6,7,8,9],[11,7,8,9]])
print(a)
print(a.shape)
print(a.dtype)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [11  7  8  9]]
(3, 4)
int32


### 5. Itemsize-size of each element in bytes


In [14]:
x=np.array([5,7,8])
print(x.itemsize)

4


 ### DIFFERENCE BETWEEN NUMPY ARRAY AND PYTHON LIST
 1. Arrays are indexed in memory in the same manner as list elements.
 2. Array takes less memory and fast to access
 3. The size of the arrays cannot be changed but list we can append.
 

In [37]:
x=np.array([5,7,8])
y=[6,7,8]
print(x[0])
print(y[0])
print(np.info(x))

5
6
class:  ndarray
shape:  (3,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x2e050ba6530
byteorder:  little
byteswap:  False
type: int32
None


###  3. The size of the arrays cannot be changed but list we can append.


In [20]:

y=[6,7,8]
y.append(8)
print(y)

[6, 7, 8, 8]


### 4. Array cannot be appended.It will give an errror

In [21]:
x=np.array([5,7,8])
x.append(9)
print(x)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

#### 2. Array contain elements of homongenous types.
#### 3. Arrays occupies much less space thanalist.
#### 4. Arrays are faster than lists.
#### 5. Arrays support vectorized operations.
     (if we applyafunction it is applied on every item.)

In [23]:
print('vectorised operation')
x=np.array([9,2,3])
x=x+1
print(x)

vectorised operation
[10  3  4]


### 2)fromiter()
      useful for creating non numeric sequence type array
      however it can create any type of array mostly used from making an array from a Dictonary

In [24]:
y={3:"d",6:"m",7:4}
x=np.fromiter(y,dtype=np.int32)
print(x)

[3 6 7]


In [25]:
y={3:"d",6:"m",6:4}
x=np.fromiter(y,dtype=np.int32)
print(x, 'when the keys are same it ignores the repeatative values')

[3 6] when the keys are same it ignores the repeatative values


In [26]:
y="ilovepython"
x=np.fromiter(y,dtype="U2")
print(x)

['i' 'l' 'o' 'v' 'e' 'p' 'y' 't' 'h' 'o' 'n']


####  3. arange() - to create an array from a range

In [32]:
x= np.arange(3,10,2,dtype=np.float32)
print(x)
print(x.shape)
print(x.itemsize)

[3. 5. 7. 9.]
(4,)
4


### 4. linspace():- creates an array equally spaced

In [33]:
x=np.linspace(3.5,10,3)
print(x,'Ending value is included')

[ 3.5   6.75 10.  ] Ending value is included


In [34]:
import numpy as np
x=np.linspace(3.5,10,3)
print(x, 'since the datatype is int so it will round up to the nearest')

[ 3.5   6.75 10.  ] since the datatype is int so it will round up to the nearest


###     2D ARRAY

In [35]:
t=((5,6,7,8),(6,7,8,9),(6,7,8,3))
a=np.array(t)
print(a ,'CREATING A 2D ARRAY FROM A TUPLE')

[[5 6 7 8]
 [6 7 8 9]
 [6 7 8 3]] CREATING A 2D ARRAY FROM A TUPLE


In [36]:
x=np.arange(6)
x=x.reshape(2,3)
print(x ,'CREATING A 2D ARRAY USING A RESHAPE')

[[0 1 2]
 [3 4 5]] CREATING A 2D ARRAY USING A RESHAPE


#### ALTERNATIVE METHODS OF CREATING AN ARRAY

 ### 1. Creating empty arrays using empty()
To create empty arrays of specified shape and dtype in
which you can store data when required.

####
Creating empty arrays using empty()
To create empty arrays ofspecified shape and dtype in
which you can store data when required.
You can also arrange elements in specific order
1. Contiguous order - row major
2. Fortran order- column major
(order="c")
(order ="f")



In [50]:
x =np.empty([3,4],dtype=np.int32,order="f")
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


 ### empty_like(), zeros_like(), ones_like()
###     To create an array similar to another existing array)having
###      similar dtype ,shape and order.

In [56]:
y =np.empty_like(x)
print(y)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [11  7  8  9]]


In [54]:
x =np.ones([3,4],dtype =np.int32)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [55]:
y =np.ones_like(x)
print(y)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [57]:
x = np.zeros((10,10),dtype = np.int64)
print(x,type(x),x.itemsize)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] <class 'numpy.ndarray'> 8


In [58]:
y = np.zeros_like(x)
print(x,type(x),x.itemsize)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] <class 'numpy.ndarray'> 8


In [59]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
x = np.ones((10,10),dtype = np.int64)
print(x,type(x),x.itemsize)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]] <class 'numpy.ndarray'> 8


In [42]:
x = np.full((5,5),7,dtype = np.int64)
print(x,type(x),x.itemsize)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]] <class 'numpy.ndarray'> 8


In [43]:
x = np.eye(10,10,dtype = np.int64)
print(x,type(x),x.itemsize)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]] <class 'numpy.ndarray'> 8


In [44]:
x = np.linspace(0,10,num =4)
print(x)

[ 0.          3.33333333  6.66666667 10.        ]


In [60]:
x= np.random.rand(3,4)
print(x)

[[0.19130765 0.92076537 0.44401181 0.82953144]
 [0.0963711  0.08127319 0.81941828 0.05639623]
 [0.30604803 0.7565242  0.76909469 0.98940132]]


In [61]:
x= np.random.rand(3,4)*100
print(x)

[[ 5.31238836 31.19544842 71.94710592 12.94443847]
 [93.84998337 78.64522432 43.97451044 29.89247391]
 [29.93434153 18.76020133 72.58995822 63.22913051]]
