# NUMPY WITH ARRAY MANIPYLATION

In [1]:
import pandas as pd
import numpy as np

In [2]:
#define and array
a = np.arange(1,5)

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a.reshape

<function ndarray.reshape>

In [5]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
 a = np.array([[1,2],[3,4]])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [11]:
y=np.append(a,[[5,6]],axis =0)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
y = np.append(a,[[8],[9]],axis=1)
y

array([[1, 2, 8],
       [3, 4, 9]])

In [ ]:
#input(arr,obj,value,axis) if there is no axis the array will flatten

In [14]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
y= np.insert(x,1,999)
y

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
# ARRAY BROADCASTING

In [19]:
y= np.insert(x,1,999,axis=0)
y

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [22]:
x= np.array([[1,2],[3,4]])

In [23]:
x

array([[1, 2],
       [3, 4]])

In [26]:
y=np.insert(x,1,999,axis=0)
y

array([[  1,   2],
       [999, 999],
       [  3,   4]])

In [27]:
y=np.insert(x,1,[7,8],axis=0)
y

array([[1, 2],
       [7, 8],
       [3, 4]])

In [34]:
max_element = np.max(y)
max_element

8

In [35]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [36]:
y =y+2
y

array([2, 3, 4, 5, 6])

In [39]:
x= np.arange(15).reshape((3,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
print('y is broadcasted into a 3x3 matrix and added')
y+x


y is broadcasted into a 3x3 matrix and added


array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])

In [42]:
x = np.arange(3)
x

array([0, 1, 2])

In [44]:
y = np.arange(3).reshape((3,1))
y

array([[0],
       [1],
       [2]])

In [46]:
print('both the arrays will be broadcasted')
x+y

both the arrays will be broadcasted


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

 # DELETE FUNCTION TAKES 3 ARRAYS AS DELETE(ARR,OBJ,AXIS=NONE/0/1)

In [47]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
print('2 will be dleted from the array')
y= np.delete(x,1)
y

2 will be dleted from the array


array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [52]:
print('first it will flatten and the it will delete')
y = np.delete(x,2)
y

first it will flatten and the it will delete


array([1, 2, 4])

In [57]:
y=np.arange(6).reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
np.concatenate((x,y))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [59]:
np.concatenate((x,y),axis =1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# 2D ARRAY

In [4]:
import numpy as np
l1=[5,6,7,8]
l2=[6,7,8,9]
l3=[10,11,12]
a=np.array([l1,l2])
print(a)

[[5 6 7 8]
 [6 7 8 9]]


In [7]:
a=np.array([[5,6,7,8],[6,7,8,9],[10,11,12,13]])
print(a)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [10 11 12 13]]


HOW ARE ARRAY STORED IN THE MEMORY

In [10]:
print(a.shape)

(3, 4)


# 2D IS, AXIS0 =1D,AXIS1=2D,RANK = NO OF AXES,SHAPE- NUMBER OF ELEMENTS ALONG EACH AXIS OF IT SHAPE IS THE FORM OF TUPLE

In [13]:
l1=[5,6,7,8]
x=np.array(l1)
x=x+1
print(x)

[6 7 8 9]


fromiter() - USED TO MAKE A 1D ARRAY MOSTLY FROM DICTONARY

In [14]:
y={3:'d',6:'m',7:4}
x=np.fromiter(y,dtype=np.int32)
print(x)

[3 6 7]


In [15]:
y={3:'d',6:'m',6:4}
x=np.fromiter(y,dtype=np.int32)
print(x)

[3 6]


In [17]:
y="python"
x=np.fromiter(y,dtype="U2")
print(x)

['p' 'y' 't' 'h' 'o' 'n']


In [18]:
y="python"
x=np.fromiter(y,dtype="U2",count=5)
print(x)

['p' 'y' 't' 'h' 'o']


# ACCESSING A 2D ARRAY

In [19]:
a= np.array([[5,6,7,8],[6,7,8,9]])
print(a[1,3])
print("first row and 3rd column")

9


In [20]:
a=np.array([[5,6,7,8],[6,7,8,9],[10,11,12,13]])
print(a[2,2])
print(a[2,-3])

12
11


# MODIFY THE VALUES OF AN ARRAY

In [23]:
a= np.array([[5,6,7,8],[6,7,8,9],[10,11,12,13]])
a[2,2]=6
print(a[2,2])
print(a,"12 is replaces with 6")

6
[[ 5  6  7  8]
 [ 6  7  8  9]
 [10 11  6 13]] 12 is replaces with 6


# ARRAY CONCATINATION,hstack() - to add horizontally
 vstack() IS USED TO ADD COLUMNS VERTICALLY

In [25]:
import numpy as np


In [27]:
l1=[5,6,7,8]
l2=[6,7,8,9]
l3=[10,11,12]
cl=np.hstack((l1,l2,l3))
print(cl)

[ 5  6  7  8  6  7  8  9 10 11 12]


 VSTACK IS USED TO ADD COLUMNS

In [29]:
l1=[5,6,7,8]
l2=[6,7,8,9]
l3=[10,11,12,13]
cl=np.vstack((l1,l2,l3))
print(cl)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [10 11 12 13]]


In [32]:
l1=np.array([[5,6,7],[6,7,8]])
l2=np.array([[10,11,12],[2,6,9]])
cl=np.vstack((l1,l2))
print(cl)

[[ 5  6  7]
 [ 6  7  8]
 [10 11 12]
 [ 2  6  9]]


# concatenate() function is used in either axis 0(columns dimention should be same) or axis 1(row dimentions should be same)

In [36]:
l1=np.array([[5,6,7],[6,7,8]])
l2=np.array([[10,11,12],[2,6,9]])
print(l1.shape)
print(l1)
print()
cl=np.concatenate((l1,l2),axis=0)
print(cl)

(2, 3)
[[5 6 7]
 [6 7 8]]

[[ 5  6  7]
 [ 6  7  8]
 [10 11 12]
 [ 2  6  9]]


In [37]:
l1=np.array([[5,6,7],[6,7,8]])
l2=np.array([[10,11,12],[2,6,9]])
cl=np.concatenate((l1,l2),axis=1)
print(cl)

[[ 5  6  7 10 11 12]
 [ 6  7  8  2  6  9]]


# TRANSPOSE OF AN ARRAY

In [40]:
l1=np.array([[5,6,7],[6,7,8],[2,1,3]])
l2=np.array([[10,11,12],[2,6,9]])
c1=np.concatenate((l1,l2.T),axis=1)
print(c1,"column size increased as hstack")

[[ 5  6  7 10  2]
 [ 6  7  8 11  6]
 [ 2  1  3 12  9]] column size increased as hstack


# AXIS NONE WILL MAKE A SINGLE ROW MATRIX

In [41]:
l1=np.array([[5,6,7],[6,7,8],[2,1,3]])
l2=np.array([[10,11,12],[2,6,9]])
c1=np.concatenate((l1,l2.T),axis=None)
print(c1,'AXIS NONE WILL MAKE A SINGLE ROW MATRIX')

[ 5  6  7  6  7  8  2  1  3 10  2 11  6 12  9] AXIS NONE WILL MAKE A SINGLE ROW MATRIX


# hsplit()vsplit(),extract()


In [43]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
y=np.hsplit(x,2)
print(y)
print(y[1])

[array([[5, 6],
       [6, 7],
       [2, 1]]), array([[7, 8],
       [8, 9],
       [3, 4]])]
[[7 8]
 [8 9]
 [3 4]]


In [44]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
y=np.vsplit(x,3)
print(y)

[array([[5, 6, 7, 8]]), array([[6, 7, 8, 9]]), array([[2, 1, 3, 4]])]


In [48]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
y=np.split(x,3)
print(y)
y=np.split(x,[2,5])
print(y)

[array([[5, 6, 7, 8]]), array([[6, 7, 8, 9]]), array([[2, 1, 3, 4]])]
[array([[5, 6, 7, 8],
       [6, 7, 8, 9]]), array([[2, 1, 3, 4]]), array([], shape=(0, 4), dtype=int32)]


In [49]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
y=np.split(x,3)
print(y)
y=np.split(x,[2,5],axis=0)
print(y)

[array([[5, 6, 7, 8]]), array([[6, 7, 8, 9]]), array([[2, 1, 3, 4]])]
[array([[5, 6, 7, 8],
       [6, 7, 8, 9]]), array([[2, 1, 3, 4]]), array([], shape=(0, 4), dtype=int32)]


In [50]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
y=np.split(x,3)
print(y)
y=np.split(x,[2,5],axis=1)
print(y,"along the column")

[array([[5, 6, 7, 8]]), array([[6, 7, 8, 9]]), array([[2, 1, 3, 4]])]
[array([[5, 6],
       [6, 7],
       [2, 1]]), array([[7, 8],
       [8, 9],
       [3, 4]]), array([], shape=(3, 0), dtype=int32)] along the column


# EXTRACT()

In [51]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
c=np.mod(x,3)==0
y=np.extract(c,x)
print(y)
print(type(y))


[6 6 9 3]
<class 'numpy.ndarray'>


In [53]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
c=np.sqrt(x)>0
y=np.extract(c,x)
print(y)
print(type(y))

[5 6 7 8 6 7 8 9 2 1 3 4]
<class 'numpy.ndarray'>


In [54]:
x=np.array([[5,6,7,8],[6,7,8,9],[2,1,3,4]])
nx=x+1
print(nx)

[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 3  2  4  5]]


In [56]:
l1=np.array([[5,6,7],[6,7,8],[2,1,3]])
l2=np.array([[10,11,12],[2,6,9],[6,7,8]])
nx=l1+l2
print(nx)

[[15 17 19]
 [ 8 13 17]
 [ 8  8 11]]


# STASTICS IS THE BRANCH OF MATHEMATICS WHICH WILL HELP TO STUDY DATA

A high posative coviarance tell that the data sets are similar, both the datasets should have same shape

In [57]:
a=np.array([5,6,4,3,2])
b=np.array([4,9,4,3,1])
c=np.cov(a,b)
print(c)

[[2.5  4.25]
 [4.25 8.7 ]]


In [58]:
print("here we are going to calculate the cov of 3 arrays which are in arrya a.SO op mat will have 9 vals")

here we are going to calculate the cov of 3 arrays which are in arrya a.SO op mat will have 9 vals


In [61]:
print("here we are going to calculate the cov of 3 arrays which are in arrya a.SO op mat will have 9 vals")
l1=np.array([[5,6,4,3,2],[6,7,8,5,3],[2,1,3,7,6]])
c=np.cov(l1)
print(c,"the more -ve values represents they are very dissimilar")

here we are going to calculate the cov of 3 arrays which are in arrya a.SO op mat will have 9 vals
[[ 2.5   2.25 -3.75]
 [ 2.25  3.7  -3.55]
 [-3.75 -3.55  6.7 ]] the more -ve values represents they are very dissimilar


# CORELATION - IF THE DATASETS ARE SAME OR DIFFERNT,DOES NOT SAY HOW MUCH SAME OR DIFFFERENT

In [62]:
a=np.array([5,6,4,3,2])
b=np.array([4,9,4,3,1])
c=np.corrcoef(a,b)
print(c)

[[1.         0.91129565]
 [0.91129565 1.        ]]


In [64]:
l1=np.array([[5,6,4,3,2],[6,7,8,5,3],[2,1,3,7,6]])
c=np.corrcoef(l1)
print(c)

[[ 1.          0.73979544 -0.91627083]
 [ 0.73979544  1.         -0.71300092]
 [-0.91627083 -0.71300092  1.        ]]


# LINEAR REGRESSION-IS USED IN THE BUSINESS TO EVALUATE TRENDS AND MAKE ESTIMATES OR FORECAST. FOR EXAMPLE IF A COMPANY SALES HAVE INCREASED STEADILY EVERY MONTH FOR THE PAST FEW YEARS, BY CONDUCTING A LINEAR ANALYSIS ON THE SALES DATA WITH MONTHLY SALES, THE COMPANY FORECAST SALES IN THE FUTURE MONTHS.
POLYFIT()


In [66]:
a=np.array([5,6,4,3,2])
b=np.array([4,9,4,3,1])
c=np.polyfit(a,b,1)
print(c)

[ 1.7 -2.6]


#  NUMPY LIBRARY