### WORKING WITH NUMPY ARRAYS MANIPULATIONS

In [1]:
import numpy as np

In [2]:
x= np.array([1,2,3,4])
x[1]

2

In [4]:
x = np.array([[1, 2, 3],[ 4, 5,6]])
print(x[1,2])            

6


In [7]:
a=np.array([[5,6,7,3],[6,7,8,9],[16,4,3,2]])
print(a[2,2])
print(a[2,-3])

3
4


### MODIFY THE VALUE IN AN ARRAY

In [10]:
a=np.array([[5,6,7,3],[6,7,8,9],[16,4,3,2]])
a[2,2]=6
print(a[2,2])
print(a[2,-3])

6
4


In [12]:
x=np.array([5,6,7,7,8,9,9])
print(x[2:5])
print(x[:5])
print(x[4:])
print(x[:5:2])
print(x[1:3])
print(x[-6:-2]) 
print(x[-6:-3:2])

[7 7 8]
[5 6 7 7 8]
[8 9 9]
[5 7 8]
[6 7]
[6 7 7 8]
[6 7]


In [13]:
x = np.arange(1,26).reshape(5,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
x[:,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [15]:
x[2,1:4]


array([12, 13, 14])

In [16]:
x[1:,4]

array([10, 15, 20, 25])

In [19]:
x=np.array([[5,6,7,7,8],[7,6,5,4,2],[5,6,4,3,2]])
print(x[:2,2:])
print()
print(x[1:2,:3])

[[7 7 8]
 [5 4 2]]

[[7 6 5]]


### 1. Combining existing arrays horizontally or vertically
### 1. hstack()
### 2. vstack()

In [4]:
l1=[1,2,3]
l2= [6,7,8]
l3=[6,8,91]
cl=np.hstack((l1,l2,l3))
print(cl)

[ 1  2  3  6  7  8  6  8 91]


In [2]:
l1=np.array([[1,2,3],[6,7,8]])
l2=np.array([[6,8,9], [6,8,9]])
cl=np.hstack((l1,l2))
print(cl)

[[1 2 3 6 8 9]
 [6 7 8 6 8 9]]


### VSTACK :- ROWS INCREASES  AND COLUMNS REMAINS CONSTANT 

In [3]:
l1=[1,2,3]
l2= [6,7,8]
l3=[6,8,91]
cl=np.vstack((l1,l2,l3))
print(cl)

[[ 1  2  3]
 [ 6  7  8]
 [ 6  8 91]]


In [4]:
l1=np.array([[1,2,3],[6,7,8]])
l2=np.array([[6,8,9], [6,8,9]])
cl=np.vstack((l1,l2))
print(cl)

[[1 2 3]
 [6 7 8]
 [6 8 9]
 [6 8 9]]


### concatenate: - perform the function in rows ie hstack(axis=1) 
###  or columns ie vstack(axis =0). The shape of the array should remain same
     

In [10]:
l1=np.array([[1,2,3],[6,7,8]])
print(l1.shape)
print(l1)

(2, 3)
[[1 2 3]
 [6 7 8]]


In [11]:
l1=np.array([[1,2,3],[6,7,8]])
l2=np.array([[6,8,9], [6,8,9]])
cl=np.concatenate((l1,l2), axis=0)
print(cl,'columns remains constant and rows increases')

[[1 2 3]
 [6 7 8]
 [6 8 9]
 [6 8 9]] columns remains constant and rows increases


In [12]:
l1=np.array([[1,2,3],[6,7,8]])
l2=np.array([[6,8,9], [6,8,9]])
cl=np.concatenate((l1,l2), axis=1)
print(cl,'rows remains constant and columns increases')

[[1 2 3 6 8 9]
 [6 7 8 6 8 9]] rows remains constant and columns increases


#### T= TRANSPOSE THE MATRIX

In [13]:
l2=np.array([[6,8,9], [6,8,9]])
print(l2.T)

[[6 6]
 [8 8]
 [9 9]]


In [20]:
l1=np.array([[1,2,3],[6,7,8],[5,8,7]])
l2=np.array([[6,8,9], [6,8,9]])
l3 =l2.T
cl=np.concatenate((l1,l3), axis=1)
print(cl)

[[1 2 3 6 6]
 [6 7 8 8 8]
 [5 8 7 9 9]]


### AXIS = NONE, IT WILL PRINT IN ONE ROW

In [23]:
l1=np.array([[1,2,3],[6,7,8],[2,1,3]])
l2=np.array([[6,8,9],[6,8,9]])
cl=np.concatenate((l1,l2), axis=None)
print(cl)

[1 2 3 6 7 8 2 1 3 6 8 9 6 8 9]


### HSPLIT() - TO SPLIT THE ARRAY INTO REQUIRED PARTS HORIZONTALLY, ROWS ARE CONSTANT AND COLUMNS INCREASES

### HSPLIT AND VSPLIT DOES NOT WORK WITH 1D ARRAY


In [24]:

x=np.array([[1,2,3,7],[6,7,8,4],[2,1,3,3]])
y =np.hsplit(x,2)
print(y)

[array([[1, 2],
       [6, 7],
       [2, 1]]), array([[3, 7],
       [8, 4],
       [3, 3]])]


#### VSPLIT ()- COLUMNS REMAIN SAME AND ROWS GET DIVIDED

In [26]:
x=np.array([[1,2,3,7],[6,7,8,4],[2,1,3,3]])
y= np.vsplit(x,1)
print(y)

[array([[1, 2, 3, 7],
       [6, 7, 8, 4],
       [2, 1, 3, 3]])]


### SPLIT():- SPLITS AN NUMPY ARRAY HORIZONTALLY AND VERTICALLY

In [29]:
x=np.array([1,2,3,7,6,7,8,4])
y=np.split(x,4)
print(y)

[array([1, 2]), array([3, 7]), array([6, 7]), array([8, 4])]


In [30]:
x=np.array([1,2,3,7,6,7,8,4])
y=np.split(x,[2,5])
print(y)

[array([1, 2]), array([3, 7, 6]), array([7, 8, 4])]


In [31]:
x=np.array([[1,2,3,8,9],[18,7,6,7,9],[8,4,8,5,3]])
y=np.split(x,[2,5],axis=0)
print(y)

[array([[ 1,  2,  3,  8,  9],
       [18,  7,  6,  7,  9]]), array([[8, 4, 8, 5, 3]]), array([], shape=(0, 5), dtype=int32)]


### 1. Obtain non contiguous subset of an array by applying condition.
### 2. Condition will be applied to each element.
###  3. Element which meets the criteria of condition is selected.
###  4. extract () will return the 1D array of values.


In [32]:
x=np.array([[1,2,3,8,9],[18,7,6,7,9],[8,4,8,5,3]])
c=np.mod(x,3)==0
y=np.extract(c,x)
print(y)
print(type(y))

[ 3  9 18  6  9  3]
<class 'numpy.ndarray'>


In [33]:
x=np.array([[1,2,3,8,9],[18,7,6,7,9],[8,4,8,5,3]])
c=np.sqrt(x)>100
y=np.extract(c,x)
print(y)
print(type(y))

[]
<class 'numpy.ndarray'>


In [34]:
x=np.array([[1,2,3,8,9],[18,7,6,7,9],[8,4,8,5,3]])
nx=x+1
print(nx)

[[ 2  3  4  9 10]
 [19  8  7  8 10]
 [ 9  5  9  6  4]]


In [35]:
x=np.array([[1,2,3,8,9],[18,7,6,7,9],[8,4,8,5,3]])
y=np.array([[1,2,3,8,9],[18,7,6,7,9],[8,4,8,5,3]])
nx = x+y
print(nx)

[[ 2  4  6 16 18]
 [36 14 12 14 18]
 [16  8 16 10  6]]
