# NUMPY STATISTICS SERIES 3

### COVARIANCE:- Compares two data sets and tells how similar or varying two data sets are
2) A high posative covariance between datasets tells they are strongly similar and high negative covariance
   explains they are highly dissimilar.
3) Shape of the datsets should be same.


In [2]:
import numpy as np
import pandas as pd
x = np.array([4,5,6,7,7,8])
y= np.array([6,4,3,4,5,5])
c=np.cov(x,y)
print(c)

[[ 2.16666667 -0.3       ]
 [-0.3         1.1       ]]


In [4]:
x= np.array([[4,5,6,7,7,8],[6,4,3,4,5,5],[1,8,4,3,9,7]])
c=np.cov(x)
print(c)

[[ 2.16666667 -0.3         2.13333333]
 [-0.3         1.1        -0.4       ]
 [ 2.13333333 -0.4         9.86666667]]


CORELATION:- When we need to know wheather two datasets are similar or different.
  Shape of the data or array should be same

In [5]:
x= np.array([[4,5,6,7,7,8],[6,4,3,4,5,5],[1,8,4,3,9,7]])
print(x)
print(np.corrcoef(x))

[[4 5 6 7 7 8]
 [6 4 3 4 5 5]
 [1 8 4 3 9 7]]
[[ 1.         -0.19432508  0.46139984]
 [-0.19432508  1.         -0.1214167 ]
 [ 0.46139984 -0.1214167   1.        ]]


LINEAR TEGRESSION :- We find out the values of a and b.which will give a straight line graph.
     We find the constand values.
    It is used in business to evaluate and make estimates or forecast. For Example if a company 
    sales have increased steadily every month for the past few years by conducting 
    linear regression analysis on the sales data with monthly sales,the company could forecast sales
    in the future.

In [7]:
x = np.array([4,5,6,7,7,8])
y = np.array([6,4,3,4,5,5])
c=np.polyfit(x,y,1)
print(c, '1 is the degree of the equation')

[-0.13846154  5.35384615] 1 is the degree of the equation
